# Generated by Django 4.2.7 on 2025-06-13 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CmsConversionFactor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(unique=True)),
                (
                    "conversion_factor",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CMS Conversion Factor",
                "verbose_name_plural": "CMS Conversion Factors",
                "db_table": "cms_conversion_factor",
            },
        ),
        migrations.CreateModel(
            name="MedicareLocalityMap",
            fields=[
                (
                    "zip_code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("locality_code", models.CharField(max_length=3)),
                ("state", models.CharField(max_length=2)),
                ("carrier", models.CharField(max_length=2)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Medicare Locality Map",
                "verbose_name_plural": "Medicare Locality Maps",
                "db_table": "medicare_locality_map",
            },
        ),
        migrations.CreateModel(
            name="MedicareLocalityMeta",
            fields=[
                (
                    "locality_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("locality_name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("carrier", models.CharField(max_length=2)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Medicare Locality Metadata",
                "verbose_name_plural": "Medicare Locality Metadata",
                "db_table": "medicare_locality_meta",
            },
        ),
        migrations.CreateModel(
            name="ProcedureCode",
            fields=[
                (
                    "procedure_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("code_type", models.CharField(max_length=10)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("subcategory", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "state_code",
                    models.CharField(
                        help_text="2-character state code (e.g., 'CA')",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_name", models.CharField(max_length=50)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("has_regions", models.BooleanField(default=False)),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_url", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_type", models.CharField(max_length=50)),
                ("region_code", models.CharField(max_length=50)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="core.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "unique_together": {("state", "region_type", "region_code")},
            },
        ),
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("schedule_type", models.CharField(max_length=50)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "conversion_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.state"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CmsRvu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("procedure_code", models.CharField(max_length=5)),
                ("year", models.IntegerField()),
                ("work_rvu", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pe_rvu", models.DecimalField(decimal_places=2, max_digits=6)),
                ("mp_rvu", models.DecimalField(decimal_places=2, max_digits=6)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CMS RVU",
                "verbose_name_plural": "CMS RVUs",
                "db_table": "cms_rvu",
                "unique_together": {("procedure_code", "year")},
            },
        ),
        migrations.CreateModel(
            name="CmsGpci",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("locality_code", models.CharField(max_length=3)),
                ("year", models.IntegerField()),
                ("work_gpci", models.DecimalField(decimal_places=4, max_digits=5)),
                ("pe_gpci", models.DecimalField(decimal_places=4, max_digits=5)),
                ("mp_gpci", models.DecimalField(decimal_places=4, max_digits=5)),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "CMS GPCI",
                "verbose_name_plural": "CMS GPCIs",
                "db_table": "cms_gpci",
                "unique_together": {("locality_code", "year")},
            },
        ),
        migrations.CreateModel(
            name="FeeScheduleRate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "modifier",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate_unit", models.CharField(default="1", max_length=20)),
                ("is_by_report", models.BooleanField(default=False)),
                ("effective_date", models.DateField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("service_type", models.TextField(blank=True, null=True)),
                ("category_id", models.TextField(blank=True, null=True)),
                ("percent_of_charge", models.TextField(blank=True, null=True)),
                ("place_of_service", models.TextField(blank=True, null=True)),
                ("code_type", models.TextField(blank=True, null=True)),
                (
                    "fee_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.feeschedule",
                    ),
                ),
                (
                    "procedure_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.procedurecode",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.region",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("fee_schedule", "procedure_code", "modifier", "region")
                },
            },
        ),
    ]
